repos:
# Official repo for the clang-format hook
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: 'v8.0.1'
  hooks:
  - id: clang-format
    files: "^adapter"
# Official repo for default hooks
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 'v4.3.0'
  hooks:
  - id: check-xml
  - id: check-merge-conflict
  - id: mixed-line-ending
    files: "^(adapter|README.md)"
  - id: trailing-whitespace
    args: [--markdown-linebreak-ext=md]
    files: "^(adapter|README.md)"
  - id: end-of-file-fixer
    files: "^(adapter|README.md)"
